#!/usr/bin/env python3
"""Generate station_map.c and station_map.h from led_map.json.

Reads mapper/ui/led_map.json (format: {"strip,pixel": "station_id", ...})
and generates C source files with a sorted lookup table for O(log n) binary
search from station_id -> list of (strip, pixel) positions.
"""

import json
import os
from collections import defaultdict

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
LED_MAP_PATH = os.path.join(PROJECT_ROOT, "mapper", "ui", "led_map.json")
OUT_DIR = os.path.join(SCRIPT_DIR, "..", "src")


def main():
    with open(LED_MAP_PATH, "r") as f:
        led_map = json.load(f)

    # Group by station_id -> list of (strip, pixel)
    station_leds = defaultdict(list)
    for key, station_id in led_map.items():
        parts = key.split(",")
        strip = int(parts[0])
        pixel = int(parts[1])
        station_leds[station_id].append((strip, pixel))

    # Sort station IDs for binary search
    sorted_stations = sorted(station_leds.keys())

    # Build flat LED position array and index array
    led_positions = []
    index_entries = []
    offset = 0
    for sid in sorted_stations:
        positions = station_leds[sid]
        count = len(positions)
        index_entries.append((sid, offset, count))
        for strip, pixel in positions:
            led_positions.append((strip, pixel))
        offset += count

    total_leds = len(led_positions)
    total_stations = len(sorted_stations)

    # Find max station ID length
    max_id_len = max(len(sid) for sid in sorted_stations)

    # Generate header
    header = f"""/* Auto-generated by gen_station_map.py - DO NOT EDIT */
#ifndef STATION_MAP_H
#define STATION_MAP_H

#include <stdint.h>

typedef struct {{
    uint8_t strip;
    uint16_t pixel;
}} led_pos_t;

#define STATION_MAP_COUNT {total_stations}
#define STATION_MAP_LED_COUNT {total_leds}
#define STATION_ID_MAX_LEN {max_id_len + 1}

/**
 * Find all LED positions for a given station stop_id.
 * Returns the number of matching LEDs (0 if not found).
 * Results are written to the results array, up to max_results entries.
 */
int station_map_find(const char *stop_id, led_pos_t *results, int max_results);

#endif /* STATION_MAP_H */
"""

    # Generate source
    source_lines = [
        '/* Auto-generated by gen_station_map.py - DO NOT EDIT */',
        '#include "station_map.h"',
        '#include <string.h>',
        '',
        '/* Flat array of all LED positions */',
        f'static const led_pos_t s_led_positions[{total_leds}] = {{',
    ]
    for i, (strip, pixel) in enumerate(led_positions):
        comma = "," if i < total_leds - 1 else ""
        source_lines.append(f"    {{{strip}, {pixel}}}{comma}")
    source_lines.append("};")
    source_lines.append("")

    # Index entry struct
    source_lines.append("typedef struct {")
    source_lines.append(f"    char stop_id[{max_id_len + 1}];")
    source_lines.append("    uint16_t offset;")
    source_lines.append("    uint8_t count;")
    source_lines.append("} station_index_t;")
    source_lines.append("")
    source_lines.append(f"/* Sorted index of {total_stations} stations */")
    source_lines.append(
        f"static const station_index_t s_station_index[{total_stations}] = {{"
    )
    for i, (sid, off, cnt) in enumerate(index_entries):
        comma = "," if i < total_stations - 1 else ""
        source_lines.append(f'    {{"{sid}", {off}, {cnt}}}{comma}')
    source_lines.append("};")
    source_lines.append("")

    # Binary search function
    source_lines.append(
        "int station_map_find(const char *stop_id, led_pos_t *results, int max_results) {"
    )
    source_lines.append("    int lo = 0;")
    source_lines.append(f"    int hi = {total_stations} - 1;")
    source_lines.append("    while (lo <= hi) {")
    source_lines.append("        int mid = (lo + hi) / 2;")
    source_lines.append(
        "        int cmp = strcmp(stop_id, s_station_index[mid].stop_id);"
    )
    source_lines.append("        if (cmp < 0) {")
    source_lines.append("            hi = mid - 1;")
    source_lines.append("        } else if (cmp > 0) {")
    source_lines.append("            lo = mid + 1;")
    source_lines.append("        } else {")
    source_lines.append("            int count = s_station_index[mid].count;")
    source_lines.append("            int offset = s_station_index[mid].offset;")
    source_lines.append(
        "            int n = count < max_results ? count : max_results;"
    )
    source_lines.append("            for (int i = 0; i < n; i++) {")
    source_lines.append(
        "                results[i] = s_led_positions[offset + i];"
    )
    source_lines.append("            }")
    source_lines.append("            return count;")
    source_lines.append("        }")
    source_lines.append("    }")
    source_lines.append("    return 0;")
    source_lines.append("}")
    source_lines.append("")

    source = "\n".join(source_lines)

    os.makedirs(OUT_DIR, exist_ok=True)

    header_path = os.path.join(OUT_DIR, "station_map.h")
    source_path = os.path.join(OUT_DIR, "station_map.c")

    with open(header_path, "w") as f:
        f.write(header)
    print(f"Generated {header_path}")

    with open(source_path, "w") as f:
        f.write(source)
    print(f"Generated {source_path}")

    print(f"Total stations: {total_stations}, Total LED positions: {total_leds}")


if __name__ == "__main__":
    main()
