#!/usr/bin/env python3
"""Generate C file with embedded wifi-manager web assets.

Creates a C source file that provides the _binary_*_start and size variables
that the wifi-manager http_app.c uses, replacing cmake EMBED_FILES.
"""

import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
WIFI_MGR_SRC = os.path.join(SCRIPT_DIR, "..", "components", "esp32-wifi-manager", "src")
OUT_FILE = os.path.join(WIFI_MGR_SRC, "embedded_files.c")
OUT_HEADER = os.path.join(WIFI_MGR_SRC, "embedded_files.h")

FILES = [
    ("style.css", "style_css"),
    ("code.js", "code_js"),
    ("index.html", "index_html"),
]


def main():
    # Generate C source
    out = []
    out.append("/* Auto-generated by gen_embed_files.py - DO NOT EDIT */")
    out.append('#include "embedded_files.h"')
    out.append("")

    # Generate header
    hdr = []
    hdr.append("/* Auto-generated by gen_embed_files.py - DO NOT EDIT */")
    hdr.append("#ifndef EMBEDDED_FILES_H")
    hdr.append("#define EMBEDDED_FILES_H")
    hdr.append("#include <stdint.h>")
    hdr.append("#include <stddef.h>")
    hdr.append("")

    for filename, varname in FILES:
        filepath = os.path.join(WIFI_MGR_SRC, filename)
        if not os.path.exists(filepath):
            print(f"WARNING: {filepath} not found, skipping")
            continue

        with open(filepath, "rb") as f:
            data = f.read()

        size = len(data)
        print(f"Embedding {filename}: {size} bytes")

        # Header declarations
        hdr.append(f"extern const uint8_t embed_{varname}_data[{size}];")
        hdr.append(f"#define EMBED_{varname.upper()}_SIZE {size}")
        hdr.append("")

        # Source definitions
        out.append(f"/* {filename} ({size} bytes) */")
        out.append(f"const uint8_t embed_{varname}_data[{size}] = {{")

        for i in range(0, size, 16):
            chunk = data[i:i + 16]
            hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
            out.append(f"    {hex_str},")

        out.append("};")
        out.append("")

    hdr.append("#endif /* EMBEDDED_FILES_H */")

    with open(OUT_FILE, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"Generated {OUT_FILE}")

    with open(OUT_HEADER, "w") as f:
        f.write("\n".join(hdr) + "\n")
    print(f"Generated {OUT_HEADER}")


if __name__ == "__main__":
    main()
