/* Auto-generated by gen_station_map.py - DO NOT EDIT */
#ifndef STATION_MAP_H
#define STATION_MAP_H

#include <stdint.h>

typedef struct {
    uint8_t strip;
    uint16_t pixel;
} led_pos_t;

#define STATION_MAP_COUNT 467
#define STATION_MAP_LED_COUNT 476
#define STATION_ID_MAX_LEN 4

/**
 * Find all LED positions for a given station stop_id.
 * Returns the number of matching LEDs (0 if not found).
 * Results are written to the results array, up to max_results entries.
 */
int station_map_find(const char *stop_id, led_pos_t *results, int max_results);

#endif /* STATION_MAP_H */
