root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/subway-server ./cmd/subway-server/"
bin = "./tmp/subway-server --port 8080 --led-map led_map.json --data-dir data --template-dir templates"
include_ext = ["go", "html", "js", "json"]
exclude_dir = ["tmp", "data", ".git"]
delay = 1000

[log]
time = false

[misc]
clean_on_exit = true
