// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/ProjectBarks/subway-pcb/server/internal/model"

func Base(title string, user *model.User, boards []model.Device, activeMAC string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\" class=\"dark\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if title != "" {
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/layout.templ`, Line: 13, Col: 11}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " | NYC Subway PCB")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "NYC Subway PCB")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</title><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin><link href=\"https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\"><script src=\"https://cdn.tailwindcss.com\"></script><script>\n\t\t\ttailwind.config = {\n\t\t\t\tdarkMode: 'class',\n\t\t\t\ttheme: {\n\t\t\t\t\textend: {\n\t\t\t\t\t\tcolors: {\n\t\t\t\t\t\t\tgold: '#c9a830',\n\t\t\t\t\t\t\tdark: {\n\t\t\t\t\t\t\t\tDEFAULT: '#0a0a0a',\n\t\t\t\t\t\t\t\tcard: '#111111',\n\t\t\t\t\t\t\t\tborder: '#1e1e1e',\n\t\t\t\t\t\t\t\thover: '#1a1a1a',\n\t\t\t\t\t\t\t},\n\t\t\t\t\t\t},\n\t\t\t\t\t\tfontFamily: {\n\t\t\t\t\t\t\tmono: ['JetBrains Mono', 'monospace'],\n\t\t\t\t\t\t},\n\t\t\t\t\t},\n\t\t\t\t},\n\t\t\t}\n\t\t</script><script src=\"https://unpkg.com/htmx.org@2.0.4\"></script><script type=\"module\" src=\"/static/dist/app-shell.js\"></script><style>\n\t\t\tbody {\n\t\t\t\tscrollbar-width: thin;\n\t\t\t\tscrollbar-color: #1e1e1e #0a0a0a;\n\t\t\t}\n\t\t\tbody::-webkit-scrollbar {\n\t\t\t\twidth: 6px;\n\t\t\t}\n\t\t\tbody::-webkit-scrollbar-track {\n\t\t\t\tbackground: #0a0a0a;\n\t\t\t}\n\t\t\tbody::-webkit-scrollbar-thumb {\n\t\t\t\tbackground: #1e1e1e;\n\t\t\t\tborder-radius: 3px;\n\t\t\t}\n\t\t\t.glass {\n\t\t\t\tbackground: rgba(17, 17, 17, 0.8);\n\t\t\t\tbackdrop-filter: blur(12px);\n\t\t\t\t-webkit-backdrop-filter: blur(12px);\n\t\t\t}\n\t\t\t@keyframes toast-fade {\n\t\t\t\t0% { opacity: 1; transform: translateY(0); }\n\t\t\t\t80% { opacity: 1; transform: translateY(0); }\n\t\t\t\t100% { opacity: 0; transform: translateY(10px); }\n\t\t\t}\n\t\t\t@keyframes pulse-subtle {\n\t\t\t\t0%, 100% { opacity: 0.6; }\n\t\t\t\t50% { opacity: 1; }\n\t\t\t}\n\t\t</style></head><body class=\"bg-dark text-gray-400 font-mono min-h-screen flex\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Nav(user, boards, activeMAC).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<main class=\"lg:ml-64 flex-1 min-h-screen\"><div class=\"p-4 pt-16 lg:p-8 lg:pt-8\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div></main><div id=\"toast-container\" class=\"fixed bottom-6 right-6 z-50 flex flex-col gap-3\"></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
