// gen-ui-exports scans sub-packages of a UI directory and generates a barrel
// file (exports_gen.go) that re-exports all public templ components, types,
// and functions so callers only need one import.
//
// Usage:
//
//	go run ./cmd/gen-ui-exports --pkg components --dir ui/components
//	go run ./cmd/gen-ui-exports --pkg ui --dir ui
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type export struct {
	Kind string // "var" or "type"
	Name string
	Ref  string // e.g. "board.BoardPage"
}

type subPkg struct {
	Name    string
	Import  string
	Exports []export
}

func main() {
	pkg := flag.String("pkg", "", "package name for the generated file")
	dir := flag.String("dir", ".", "directory to scan for sub-packages")
	flag.Parse()

	if *pkg == "" {
		log.Fatal("--pkg is required")
	}

	absDir, err := filepath.Abs(*dir)
	if err != nil {
		log.Fatalf("resolve dir: %v", err)
	}

	modPath := findModulePath(absDir)
	pkgs := scanSubPackages(absDir, modPath)
	writeExports(absDir, *pkg, pkgs)
}

func scanSubPackages(absDir, modPath string) []subPkg {
	entries, err := os.ReadDir(absDir)
	if err != nil {
		log.Fatalf("read dir %s: %v", absDir, err)
	}

	var pkgs []subPkg

	for _, e := range entries {
		if !e.IsDir() || e.Name() == "lib" || strings.HasPrefix(e.Name(), ".") {
			continue
		}

		subDir := filepath.Join(absDir, e.Name())
		pkgName := e.Name()
		importPath := modPath + "/" + e.Name()

		exports := parseExports(subDir, pkgName)
		if len(exports) > 0 {
			pkgs = append(pkgs, subPkg{
				Name:    pkgName,
				Import:  importPath,
				Exports: exports,
			})
		}
	}

	sort.Slice(pkgs, func(i, j int) bool { return pkgs[i].Name < pkgs[j].Name })
	return pkgs
}

func parseExports(dir, pkgName string) []export {
	fset := token.NewFileSet()
	pkgMap, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		name := fi.Name()
		return strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go")
	}, 0)
	if err != nil {
		log.Printf("warning: parse %s: %v", dir, err)
		return nil
	}

	seen := make(map[string]bool)
	var exports []export

	for _, astPkg := range pkgMap {
		for _, file := range astPkg.Files {
			for _, decl := range file.Decls {
				switch d := decl.(type) {
				case *ast.FuncDecl:
					if d.Recv != nil || !d.Name.IsExported() {
						continue
					}
					if !seen[d.Name.Name] {
						seen[d.Name.Name] = true
						exports = append(exports, export{
							Kind: "var",
							Name: d.Name.Name,
							Ref:  pkgName + "." + d.Name.Name,
						})
					}
				case *ast.GenDecl:
					for _, spec := range d.Specs {
						switch s := spec.(type) {
						case *ast.TypeSpec:
							if s.Name.IsExported() && !seen[s.Name.Name] {
								seen[s.Name.Name] = true
								exports = append(exports, export{
									Kind: "type",
									Name: s.Name.Name,
									Ref:  pkgName + "." + s.Name.Name,
								})
							}
						case *ast.ValueSpec:
							for _, name := range s.Names {
								if name.IsExported() && !seen[name.Name] {
									seen[name.Name] = true
									exports = append(exports, export{
										Kind: "var",
										Name: name.Name,
										Ref:  pkgName + "." + name.Name,
									})
								}
							}
						}
					}
				}
			}
		}
	}

	sort.Slice(exports, func(i, j int) bool { return exports[i].Name < exports[j].Name })
	return exports
}

func writeExports(absDir, pkg string, pkgs []subPkg) {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by gen-ui-exports; DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkg)

	if len(pkgs) > 0 {
		fmt.Fprintf(&buf, "import (\n")
		for _, p := range pkgs {
			fmt.Fprintf(&buf, "\t\"%s\"\n", p.Import)
		}
		fmt.Fprintf(&buf, ")\n")
	}

	total := 0
	for _, p := range pkgs {
		fmt.Fprintf(&buf, "\n// --- %s ---\n", p.Name)
		for _, e := range p.Exports {
			switch e.Kind {
			case "var":
				fmt.Fprintf(&buf, "var %s = %s\n", e.Name, e.Ref)
			case "type":
				fmt.Fprintf(&buf, "type %s = %s\n", e.Name, e.Ref)
			}
			total++
		}
	}

	outPath := filepath.Join(absDir, "exports_gen.go")
	if err := os.WriteFile(outPath, buf.Bytes(), 0644); err != nil {
		log.Fatalf("write %s: %v", outPath, err)
	}
	fmt.Printf("wrote %s (%d packages, %d exports)\n", outPath, len(pkgs), total)
}

func findModulePath(dir string) string {
	d := dir
	for {
		modFile := filepath.Join(d, "go.mod")
		data, err := os.ReadFile(modFile)
		if err == nil {
			for _, line := range strings.Split(string(data), "\n") {
				line = strings.TrimSpace(line)
				if strings.HasPrefix(line, "module ") {
					mod := strings.TrimSpace(strings.TrimPrefix(line, "module"))
					rel, _ := filepath.Rel(d, dir)
					if rel == "." {
						return mod
					}
					return mod + "/" + filepath.ToSlash(rel)
				}
			}
		}
		parent := filepath.Dir(d)
		if parent == d {
			log.Fatal("could not find go.mod")
		}
		d = parent
	}
}
