/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "subway.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(subway_Train, subway_Train, AUTO)


PB_BIND(subway_Station, subway_Station, AUTO)


PB_BIND(subway_DeviceState, subway_DeviceState, 4)


PB_BIND(subway_DeviceState_ConfigEntry, subway_DeviceState_ConfigEntry, AUTO)


PB_BIND(subway_DeviceBoard, subway_DeviceBoard, 4)


PB_BIND(subway_DeviceBoard_LedMapEntry, subway_DeviceBoard_LedMapEntry, AUTO)


PB_BIND(subway_DeviceDiagnostics, subway_DeviceDiagnostics, 2)


PB_BIND(subway_DeviceDiagnostics_System, subway_DeviceDiagnostics_System, AUTO)


PB_BIND(subway_DeviceDiagnostics_Fetch, subway_DeviceDiagnostics_Fetch, AUTO)


PB_BIND(subway_DeviceDiagnostics_Lua, subway_DeviceDiagnostics_Lua, AUTO)


PB_BIND(subway_DeviceDiagnostics_Render, subway_DeviceDiagnostics_Render, AUTO)


PB_BIND(subway_DeviceScript, subway_DeviceScript, 4)


PB_BIND(subway_DeviceScript_ConfigEntry, subway_DeviceScript_ConfigEntry, AUTO)





