/* Auto-generated by gen_embed_files.py - DO NOT EDIT */
#ifndef EMBEDDED_FILES_H
#define EMBEDDED_FILES_H
#include <stdint.h>
#include <stddef.h>

extern const uint8_t embed_style_css_data[7888];
#define EMBED_STYLE_CSS_SIZE 7888

extern const uint8_t embed_code_js_data[9723];
#define EMBED_CODE_JS_SIZE 9723

extern const uint8_t embed_index_html_data[4620];
#define EMBED_INDEX_HTML_SIZE 4620

#endif /* EMBEDDED_FILES_H */
