; PlatformIO Project Configuration File

[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = espidf
board_build.partitions = partitions.csv
monitor_speed = 115200

build_flags =
    -Iproto

lib_deps =
    nanopb/Nanopb@^0.4.9
